apiVersion: v1  
kind: Service                                 # Type of the kubernetes resource
metadata:
  name: ecommerce-bot                # Name of the Kubernetes resource
  labels:                                     # Labels that will be applied to the resource
    app: ecommerce-bot
spec:
  type: NodePort                              # Gives each node an external IP that’s accessible from outside the cluster and also opens a Port.
  selector:
    app: ecommerce-bot               # Selects any Pod with labels `app=fullstack-app-postgres`
  ports: 
  - name: http
    port: 8007
    targetPort: 8007